os:
  - linux
  # - osx

language: c

compiler:
  - gcc
  - clang

# Intel Power Gadget won't install in Travis - no point in running on OSX then...
# Error - Intel Power Gadget does not currently support systems with more than one CPU package.
# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install intel-power-gadget; fi

install:
  # powercap dependency
  - git clone https://github.com/powercap/powercap.git libpowercap
  - cd libpowercap
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=_install ..
  - cmake --build . --target install
  - cd ../..
  # libmsr dependency (force version 0.3.0) (force Ivy Bridge architecture)
  - git clone https://github.com/LLNL/libmsr.git libmsr_src
  - cd libmsr_src
  - git checkout v0.3.0
  # libmsr only claims to support gcc, so don't let it build with clang
  - CC=gcc ./install.sh _install -f3E
  - cd ..

script:
  - mkdir _build
  - cd _build
  # Test build with stricter flags
  - export CFLAGS="-D_FORTIFY_SOURCE=2 -fstack-protector -g3 -pedantic -W -Wall -Wbad-function-cast -Wcast-align
      -Wcast-qual -Wdisabled-optimization -Wendif-labels -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Winline
      -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unused-parameter -Wpointer-arith -Wshadow
      -Wstrict-prototypes -Wstack-protector -Wswitch -Wundef -Wwrite-strings"
  - PKG_CONFIG_PATH="../libpowercap/_build/_install/lib/pkgconfig" cmake .. -DCMAKE_PREFIX_PATH="`pwd`/../libmsr_src/_install/" -DCMAKE_C_FLAGS="$CFLAGS"
  - cmake --build .
  - ctest --verbose
